# Generated by Django 6.0.5 on 2026-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=255)),
                ('bookAuthor', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('isAvailable', models.BooleanField()),
            ],
        ),
    ]
